"""Standalone real Celery processes; replace only the external text provider."""

import asyncio
import json
import os
from pathlib import Path
import re
import sys
from uuid import UUID, uuid4

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.testing import REDIS_VISIBILITY_TIMEOUT, configure_test_settings  # noqa: E402


def main():
    directory = Path(os.environ["TEST_RUNTIME_DIR"])
    schema = os.environ["TEST_DATABASE_SCHEMA"]
    assert re.fullmatch(r"migration_[0-9a-f]{32}", schema)
    settings = configure_test_settings(
        database_url=os.environ["TEST_DATABASE_URL"],
        broker_url=os.environ["TEST_BROKER_URL"],
        result_backend=os.environ["TEST_RESULT_BACKEND"],
        log_dir=str(directory / "app-logs"),
    )
    settings.celery_task_retry_countdown_seconds = 1
    settings.apimart_api_key = "isolated-provider-placeholder"
    from app.db import session

    session.engine.update_execution_options(schema_translate_map={None: schema})
    sessions = session.create_worker_sessionmaker()
    sessions.kw["bind"].update_execution_options(schema_translate_map={None: schema})
    from sqlalchemy import event as sqlalchemy_event

    def set_search_path(connection, record):
        # Trigger SQL also needs the isolated schema; schema_translate_map only covers ORM SQL.
        cursor = connection.cursor()
        cursor.execute(f'SET search_path TO "{schema}"')
        cursor.close()

    for engine in (session.engine, sessions.kw["bind"]):
        sqlalchemy_event.listen(engine.sync_engine, "connect", set_search_path)
    from app.worker import celery_app
    from app.tasks import canvas_generation
    from app.services.generation.runner import ModelRunResult
    from app.core.exceptions import AppException
    from celery.signals import task_postrun, task_prerun, worker_ready

    # Bound redelivery time for process-crash tests; production keeps its long timeout.
    celery_app.conf.broker_transport_options = {
        "visibility_timeout": REDIS_VISIBILITY_TIMEOUT,
        "polling_interval": 0.1,
    }

    def event(kind, **values):
        with (directory / "events.jsonl").open("a") as stream:
            stream.write(json.dumps({"kind": kind, **values}) + "\n")

    async def model_result(*args, idempotency_key=None, **kwargs):
        event("provider", task_id=idempotency_key)
        fail_once = directory / "provider-failed"
        if os.getenv("TEST_PROVIDER_RETRY") == "1" and not fail_once.exists():
            fail_once.touch()
            raise AppException("controlled provider outage", code=50202, status_code=503)
        return ModelRunResult(content="Generated by test provider", extra={"credits_cost": "1"})

    canvas_generation.run_model = model_result

    @worker_ready.connect(weak=False)
    def ready(**kwargs):
        (directory / f"{os.environ['TEST_PROCESS_NAME']}.ready").touch()

    @task_prerun.connect(weak=False)
    def received(task_id=None, task=None, **kwargs):
        event("received", task_id=task_id, task_name=task.name)

    @task_postrun.connect(weak=False)
    def crash_before_ack(task_id=None, task=None, state=None, **kwargs):
        event("finished", task_id=task_id, task_name=task.name, state=state)
        marker = directory / "crashed-before-ack"
        if (
            os.getenv("TEST_CRASH_BEFORE_ACK") == "1"
            and state == "SUCCESS"
            and task.name == canvas_generation.run_canvas_generation.name
            and not marker.exists()
        ):
            marker.touch()
            os._exit(17)

    mode = sys.argv[1]
    if mode == "worker":
        celery_app.worker_main(
            [
                "worker",
                "--pool=solo",
                "--concurrency=1",
                "--loglevel=INFO",
                "--without-gossip",
                "--without-mingle",
                "--without-heartbeat",
                "--queues=story_ai_default,story_ai_text",
                "--hostname=opt13@%h",
            ]
        )
    elif mode == "beat":
        celery_app.start(
            [
                "beat",
                "--loglevel=INFO",
                "--schedule",
                str(directory / "beat-schedule"),
                "--pidfile",
                str(directory / "beat.pid"),
            ]
        )
    elif mode == "submit":
        asyncio.run(submit(sessions))
    else:
        raise ValueError("unknown test process mode")


async def submit(sessions):
    from app.schemas.canvas_generation import CanvasGenerationSubmit
    from app.services.projects import canvas_generations

    if os.getenv("TEST_EXIT_AFTER_COMMIT") == "1":

        async def exit_after_commit(*args):
            os._exit(0)

        canvas_generations.dispatch_tasks_best_effort = exit_after_commit
    async with sessions() as db:
        await canvas_generations.submit_generation(
            db,
            UUID(os.environ["TEST_PROJECT_ID"]),
            UUID(os.environ["TEST_USER_ID"]),
            UUID(os.environ["TEST_CANVAS_ID"]),
            UUID(os.environ["TEST_NODE_ID"]),
            CanvasGenerationSubmit(expected_content_revision=1, idempotency_key=uuid4()),
        )


if __name__ == "__main__":
    main()
